# Generated by Django 5.2.6 on 2025-09-05 14:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_completos', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('contraseña', models.CharField(default='', max_length=128)),
                ('cedula', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='GestionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefonico', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='GestionGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.IntegerField()),
                ('descripcion_garantia', models.TextField(max_length=255)),
                ('fecha_garantia', models.DateField()),
                ('estado_garantia', models.CharField(default='ACTIVA', max_length=20)),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
            },
        ),
        migrations.CreateModel(
            name='GestionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=80, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('logo_marca', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='PresentacionTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=25)),
                ('funcion_principal', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Tipo de Presentación',
                'verbose_name_plural': 'Tipos de Presentación',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento_nit', models.CharField(max_length=15, unique=True)),
                ('direccion_empresa', models.CharField(max_length=30)),
                ('numero_telefonico', models.CharField(max_length=15)),
                ('descripcion', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField()),
                ('fecha_facturacion', models.DateField()),
                ('descripcion_venta', models.TextField(max_length=255)),
                ('terminos_condiciones', models.TextField(max_length=255)),
                ('nit', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.administrador')),
                ('id_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.gestionservicio')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_producto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado_producto', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='mi_app.categoria')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='mi_app.marca')),
                ('id_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='mi_app.presentaciontipo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='GestionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('departamento_entrega', models.CharField(max_length=50)),
                ('municipio_ciudad_entrega', models.CharField(max_length=50)),
                ('direccion_entrega', models.CharField(max_length=50)),
                ('comprobante_pago', models.CharField(max_length=50)),
                ('estado_pedido', models.CharField(default='PENDIENTE', max_length=20)),
                ('numero_gestion_de_venta', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.gestioncliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento_nit_proveedor', models.CharField(max_length=15)),
                ('cantidad_productos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.TextField(blank=True, max_length=60)),
                ('fecha_compra', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.administrador')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.producto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante_pago', models.CharField(max_length=50)),
                ('fecha_venta', models.DateField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.administrador')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.gestionpedido')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
