# Generated by Django 5.2.6 on 2025-09-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestioncliente',
            name='numero_telefonico',
        ),
    ]
