# Generated by Django 5.2.6 on 2025-09-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestiongarantia',
            name='estado_garantia',
            field=models.CharField(choices=[('PENDIENTE', 'pendiente'), ('APROVADO', 'aprovado'), ('RECHAZADO', 'rechazado')], max_length=20),
        ),
    ]
