# Generated by Django 5.2.6 on 2025-09-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_gestiongarantia_estado_garantia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionpedido',
            name='numero_gestion_de_venta',
        ),
        migrations.AlterField(
            model_name='gestiongarantia',
            name='id_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantias_factura', to='mi_app.facturacion'),
        ),
        migrations.AlterField(
            model_name='gestionpedido',
            name='comprobante_pago',
            field=models.CharField(default='pago exitoso', max_length=50),
        ),
        migrations.AlterField(
            model_name='gestionpedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PROCESO', 'proceso'), ('PEDIDO EXITOSO', 'pedido exitoso')], max_length=20),
        ),
    ]
