# Generated by Django 5.2.6 on 2025-09-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_remove_gestioncliente_numero_telefonico'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestioncliente',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
