# Generated by Django 5.2.6 on 2025-09-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_gestioncliente_numero_telefonico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestioncliente',
            name='nombre_completo',
            field=models.CharField(max_length=100),
        ),
    ]
