# Generated by Django 5.2.6 on 2025-09-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_remove_gestionpedido_numero_gestion_de_venta_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facturacion',
            new_name='Factura',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='fecha_facturacion',
            new_name='fecha_factura',
        ),
    ]
