# Generated by Django 5.2.6 on 2025-09-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_rename_facturacion_factura_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GestionGarantia',
            new_name='Garantia',
        ),
    ]
