# Generated by Django 5.2.6 on 2025-09-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_rename_gestiongarantia_garantia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GestionPedido',
            new_name='Pedido',
        ),
    ]
